version: 2.1

orbs:
  node: circleci/node@4.7
  windows: circleci/windows@2.4.1
  codecov: codecov/codecov@1.0.2

executors:
  linux:
    machine:
      image: 'ubuntu-2004:202107-02'
  macos:
    macos:
      xcode: 13.0.0

jobs:
  build:
    parameters:
      executor:
        type: executor
      node-version:
        type: string
    executor: << parameters.executor >>
    steps:
      - when:
          condition:
            equal: [windows, << parameters.executor >>]
          steps:
            - run:
                name: Increase Windows port limit and reduce time wait delay
                command: |
                  REG ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TCPIP\Parameters /v MaxUserPort /t REG_DWORD /d 32768 /f
                  REG ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TCPIP\Parameters /v TcpTimedWaitDelay /t REG_DWORD /d 30 /f
      - checkout
      - node/install:
          node-version: << parameters.node-version >>
      - run:
          name: Install core dependencies
          command: npm ci --no-audit
      - run:
          name: Install site dependencies
          command: npm run site:build:install
      - unless:
          condition:
            equal: ['10', << parameters.node-version >>]
          steps:
            - run:
                name: Linting
                command: npm run format:ci
      - run:
          # GitHub secrets are not available when running on PR from forks
          # We set a flag so we can skip tests that access Netlify API
          name: Setup NETLIFY_TEST_DISABLE_LIVE environment variable
          command: |
            if [ -z "${CIRCLE_PR_NUMBER}" ]; then
              echo 'export NETLIFY_TEST_DISABLE_LIVE=false' >> $BASH_ENV
            else
              echo 'export NETLIFY_TEST_DISABLE_LIVE=true' >> $BASH_ENV
            fi
      - run:
          name: Test
          command: npm run test:ci
          environment:
            # Changes the polling interval used by the file watcher
            CHOKIDAR_INTERVAL: 20
            CHOKIDAR_USEPOLLING: 1
      - codecov/upload:
          file: coverage/coverage-final.json

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              executor: [linux, macos, windows/default]
              node-version: ['10', 'node']
            exclude:
              - macos: '10'
              - windows: '10'
# missing: fail-fast
# missing: ignore docs/** changes
# missing: 30 minutes timeout
