version: 2.1

orbs:
  node: circleci/node@4.7
  windows: circleci/windows@2.4.1
  codecov: codecov/codecov@1.0.2

executors:
  linux:
    machine:
      image: 'ubuntu-2004:202107-02'
  macos:
    macos:
      xcode: 13.0.0

jobs:
  build:
    parameters:
      executor:
        type: string
      node-version:
        type: string
    executor: << parameters.executor >>
    steps:
      - when:
          condition:
            equal: [windows/default, << parameters.executor >>]
          steps:
            - run:
                name: Increase Windows port limit and reduce time wait delay
                command: |
                  REG ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TCPIP\Parameters /v MaxUserPort /t REG_DWORD /d 32768 /f
                  REG ADD HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\TCPIP\Parameters /v TcpTimedWaitDelay /t REG_DWORD /d 30 /f
            - run:
                # GitHub secrets are not available when running on PR from forks
                # We set a flag so we can skip tests that access Netlify API
                name: Setup NETLIFY_TEST_DISABLE_LIVE environment variable
                command: |
                  if ($null -eq $env:CIRCLE_PR_NUMBER) {
                      [Environment]::SetEnvironmentVariable('NETLIFY_TEST_DISABLE_LIVE', 'false', 'User')
                  } else {
                      [Environment]::SetEnvironmentVariable('NETLIFY_TEST_DISABLE_LIVE', 'true', 'User')
                  }
      - when:
          # The linux machine doesn't come with Git LFS
          condition:
            equal: [linux, << parameters.executor >>]
          steps:
            - run:
                name: Install Git LFS
                command: |
                  curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
                  sudo apt-get install git-lfs
      - checkout
      - when:
          condition:
            or:
              - equal: [linux, << parameters.executor >>]
              - equal: [macos, << parameters.executor >>]
          steps:
            # This orb doesn't support Windows
            - node/install:
                node-version: << parameters.node-version >>
                # We use the npm version that comes with Node.js
                install-npm: false
            - run:
                # GitHub secrets are not available when running on PR from forks
                # We set a flag so we can skip tests that access Netlify API
                name: Setup NETLIFY_TEST_DISABLE_LIVE environment variable
                command: |
                  if [ -z "${CIRCLE_PR_NUMBER}" ]; then
                    echo 'export NETLIFY_TEST_DISABLE_LIVE=false' >> $BASH_ENV
                  else
                    echo 'export NETLIFY_TEST_DISABLE_LIVE=true' >> $BASH_ENV
                  fi
      - run:
          name: Install core dependencies
          command: npm ci --no-audit
      - run:
          name: Install site dependencies
          command: npm run site:build:install
      - unless:
          condition:
            equal: ['10', << parameters.node-version >>]
          steps:
            - run:
                name: Linting
                command: npm run format:ci
      - run:
          name: Test
          command: npm run test:ci
          environment:
            # Changes the polling interval used by the file watcher
            CHOKIDAR_INTERVAL: 20
            CHOKIDAR_USEPOLLING: 1
      - codecov/upload:
          file: coverage/coverage-final.json
          flags: << parameters.executor >>,<< parameters.node-version >>

workflows:
  all-tests:
    jobs:
      - build:
          matrix:
            parameters:
              executor: [linux, macos, windows/default]
              node-version: ['10', 'node']
            exclude:
              - executor: 'macos'
                node-version: '10'
              - executor: 'windows/default'
                node-version: '10'
# missing: ignore docs/** changes
